apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-13-quotes-flask # remember to change this!
  namespace: argocd
spec:
  project: student-13-project # remember to change this to your project name!
  source:
    repoURL: 'https://github.com/eficode-academy/argocd-katas.git'
    path: quotes-flask/k8s
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: student-13 # remember to change this to your namespace!
