apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-13-jenkins
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: student-13
  syncPolicy:
    automated: {}
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      targetRevision: 12.4.0
      helm:
        valueFiles:
          - $values/jenkins/values.yaml
      chart: jenkins
    - repoURL: 'https://github.com/smoore1987/argocd-katas'
      targetRevision: main
      ref: values